apiVersion: v1
kind: Service
metadata: 
  name: postgres-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 5432 
  selector:
    name: postgres-pod
    app: example-voting-app
