apiVersion: v1
kind: Pod
metadata: 
  name: voting-app-pod
  labels:
    app: voting-app
spec:
  containers:
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_ROOT_PASSWORD
          value: mysecretpassword
