apiVersion: v1
kind: Pod
metadata: 
  name: result-app-pod
  labels:
    name: result-app-pod 
    app: example-voting-app
spec:
  containers:
    - name: result-pod
      image: mahi2698/example-voting-app/vote
      port:
        - containerPort: 80
