apiVersion: v1
kind: Pod
metadata: 
  name: voting-app-pod
  labels:
    name: voting-app-pod 
    app: example-voting-app
spec:
  containers:
    - name: voting-app-pod
      image: mahi2698/example-voting-app/result
      ports:
        - containerPort: 80
