apiVersion: v1
kind: Pod
metadata: 
  name: worker-app-pod
  labels:
    name: worker-app-pod 
    app: example-voting-app
spec:
  containers:
    - name: worker-app-pod
      image: mahi2698/example-voting-app/worker
      
